name : CI
on   : [push, pull_request]
jobs :
    lint:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm install -g yarn
            - run: node -v
            - run: yarn install
            - run: yarn lint
