name: Publication
on:
    push:
        tags: ['*']
jobs:
    "Publish":
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with: { node-version: '18' }
            - run: npm ci
            - run: npm run publish-all -- --yes
