name : Publication
on:
    push:
        tags: ['*']
jobs:
    build:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn lint --max-warnings 0 --color
    publish:
        needs   : build
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                registry-url : https://npm.pkg.github.com/
                scope        : '@pulsanova'
            - run: yarn install
            - run: yarn publish-all --yes
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
